### ISSUE TITLE
Issues with the missing data flag -j option

### ISSUE THREAD

**Issue by hilge** [spiros/tofu#1]
Hi Spiros,

The -j flag does not seem to work without specifying specific fields and in some cases does not work depending on the input numbers used. See issue below

```
python tofu.py -n 100 -j 5
  0%|                                                                                                               | 7/7450 [00:00<04:28, 27.68it/s]
Traceback (most recent call last):
  File "tofu.py", line 96, in <module>
    args.jitter)
  File "/home/johan/projects/tofu/helpers.py", line 238, in insert_missingness
    a[i] = np.nan
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 4260, in __setitem__
    raise TypeError("Index does not support mutable operations")
TypeError: Index does not support mutable operations

```
Oddly enough this combination  work

`python tofu.py -n 20 -j 1`

but not this one

`python tofu.py -n 100 -j 1
`
Best Johan and Kenan

**Comment by spiros** [comment]
thanks, well spotted, fixed
